### ISSUE TITLE
请问如何给这个圆形进度条加上一点弧度

### ISSUE THREAD

**Issue by sonofmagic** [ronffy/wepy-com-progress-circle#2]
![image](https://user-images.githubusercontent.com/15621541/53717584-8d1b4500-3e93-11e9-9cab-18891e4a2e66.png)

类似这样的效果，加了一点圆角

**Comment by ronffy** [comment]
@sonofmagic  
Sorry，该组件无法实现。
圆角效果一般是用 SVG 实现的，不过考虑小程序对 SVG 的限制，该项目组件并未使用 SVG 技术，而是基于 CSS 实现的，鉴于实现方式，无法满足该需求。
